import React, { useEffect, useState } from "react";
import {
  Tooltip,
  Legend,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";
import {
  subMonths,
  format,
} from "date-fns";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { useDispatch, useSelector } from "react-redux";
import { AppDispatch, RootState } from "../store";
import {
  getCategoryExpenseThunk,
  getMontlyExpenseThunk,
  getTotalSummaryThunk,
} from "../store/thunk/transaction/summary/summary.thunk";

const COLORS = [
  "#8884d8",
  "#82ca9d",
  "#ffc658",
  "#ff8042",
  "#8dd1e1",
  "#a4de6c",
  "#d0ed57",
  "#ffc0cb",
];

const Dashboard: React.FC = () => {

  const dispatch = useDispatch<AppDispatch>();
  const { totalSummary, categoryExpense } = useSelector(
    (state: RootState) => state.summary
  );

  const [totalBalance, setTotalBalance] = useState(0);
  const [totalIncome, setTotalIncome] = useState(0);
  const [totalExpenses, setTotalExpenses] = useState(0);
  
  const savingsRate = totalIncome > 0 ? (totalBalance / totalIncome) * 100 : 0;
  const expenseChange = 0;
  
  const monthlyData = Array.from({ length: 6 }, (_, i) => {
    const month = subMonths(new Date(), 5 - i);
  

    return {
      month: format(month, "MMM yyyy"),
      monthDate: month,
      
    };
  });

  


  

  // PDF Export function
  const handleExportPDF = () => {
    try {
      // Initialize jsPDF with proper typing
      const doc = new jsPDF() as jsPDF & {
        lastAutoTable?: { finalY: number };
        autoTable?: (options: any) => jsPDF;
      };

      // Title
      doc.setFontSize(18);
      doc.text("Financial Dashboard Summary", 14, 20);

      // Summary Section
      doc.setFontSize(12);
      doc.text("Overview:", 14, 30);

      // First table
      autoTable(doc, {
        startY: 34,
        head: [["Metric", "Value"]],
        body: [
          ["Total Income", `$${totalIncome.toFixed(2)}`],
          ["Total Expenses", `$${totalExpenses.toFixed(2)}`],
          ["Balance", `$${totalBalance.toFixed(2)}`],
          ["Savings Rate", `${savingsRate.toFixed(1)}%`],
          
        ],
        theme: "striped",
      });

      // Save the file
      doc.save("financial_dashboard_summary.pdf");
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    }
  };

  const handleExportExcel = () => {
    try {
      const wb = XLSX.utils.book_new();
      const exportTime = new Date().toLocaleString();

      const addSheet = (
        data: any[][],
        sheetName: string,
        colWidths: number[] = [25, 25, 25, 25, 25]
      ) => {
        const ws = XLSX.utils.aoa_to_sheet(data);
        ws["!cols"] = colWidths.map((w) => ({ wch: w }));
        XLSX.utils.book_append_sheet(wb, ws, sheetName);
      };

      // 1. Overview Sheet
      const overviewData = [
        ["📊 Financial Dashboard Summary"],
        [],
        ["Overview"],
        ["Metric", "Value"],
      ];
      addSheet(overviewData, "Overview", [40, 30]);

      // 2. Monthly Data Sheet
      const monthlyDataSheet = [
        ["6-Month Income, Expenses, and Savings"],
        [],
        ["Month", "Income", "Expenses", "Savings"],
        ...monthlyData.map((d) => [
          d.month,
        ]),
      ];
      addSheet(monthlyDataSheet, "Monthly Data", [20, 20, 20, 20]);

      // 3. Budget Utilization Sheet
      const budgetUtilSheet = [
        ["Budget Utilization Summary"],
        [],
        ["Category", "Budget", "Spent", "Remaining", "Utilization"],
        
      ];
      addSheet(budgetUtilSheet, "Budget Utilization", [25, 20, 20, 20, 20]);

      // 4. Category Spending Sheet
      const categorySheet = [
        ["Category-wise Spending"],
        [],
        ["Category", "Amount Spent"],
       
      ];
      addSheet(categorySheet, "Category Spending", [30, 20]);

      // 5. Export Info Sheet
      const exportInfo = [
        ["Export Metadata"],
        [],
        ["Generated By", "Financial Dashboard App"],
        ["Exported At", exportTime],
      ];
      addSheet(exportInfo, "Export Info", [25, 40]);

      // Save Excel file
      XLSX.writeFile(wb, "financial_dashboard.xlsx");
    } catch (error) {
      console.error("Error generating Excel:", error);
      alert("Failed to generate Excel file. Please try again.");
    }
  };



  useEffect(() => {
    // Fetch transactions and budgets when the component mounts
    const fetchData = async () => {
      await dispatch(getTotalSummaryThunk());
      await dispatch(getCategoryExpenseThunk());
      await dispatch(getMontlyExpenseThunk());
    };
    fetchData();
  
    if (totalSummary) {
      setTotalBalance(totalSummary?.balance);
      setTotalIncome(totalSummary?.totalIncome);
      setTotalExpenses(totalSummary?.totalExpense);
    }
  }, [totalSummary]);

  return (
    <div className="ml-14 pl-12 p-4">
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 mb-6">
        <h1 className="text-2xl font-bold text-gray-800">
          Financial Dashboard
        </h1>

        <div className="flex gap-3">
          <button
            onClick={handleExportPDF}
            className="px-4 py-2 bg-blue-600 text-white rounded shadow hover:bg-blue-700 transition-colors"
          >
            Export PDF
          </button>
          <button
            onClick={handleExportExcel}
            className="px-4 py-2 bg-green-600 text-white rounded shadow hover:bg-green-700 transition-colors"
          >
            Export Excel
          </button>
        </div>
      </div>

      {/* Stat Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-6">
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold mb-2">Total Balance</h2>
          <p
            className={`text-3xl font-bold ${
              totalBalance >= 0 ? "text-green-600" : "text-red-600"
            }`}
          >
           ₹{totalBalance}
          </p>
          <p className="text-sm text-gray-600 mt-2">Current month</p>
        </div>
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold mb-2">Total Income</h2>
          <p className="text-3xl font-bold text-green-600">
            ₹{totalIncome}
          </p>
          <p className="text-sm text-gray-600 mt-2">Current month</p>
        </div>
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold mb-2">Total Expenses</h2>
          <p className="text-3xl font-bold text-red-600">
           ₹{totalExpenses}
          </p>
          <p
            className={`text-sm mt-2 ${
              expenseChange > 0 ? "text-red-500" : "text-green-500"
            }`}
          >
            {expenseChange > 0 ? "↑" : "↓"} {Math.abs(expenseChange).toFixed(1)}
            % vs last month
          </p>
        </div>
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold mb-2">Savings Rate</h2>
          <p className="text-3xl font-bold text-blue-600">
            {savingsRate.toFixed(1)}%
          </p>
          <p className="text-sm text-gray-600 mt-2">of income saved</p>
        </div>
      </div>

      {/* Charts Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
        {/* Income vs Expenses Pie Chart */}
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold mb-4">Income vs Expenses</h2>
          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie
                data={[
                  { name: "Income", value: totalIncome },
                  { name: "Expenses", value: totalExpenses },
                ]}
                dataKey="value"
                nameKey="name"
                cx="50%"
                cy="50%"
                outerRadius={100}
                label={({ name, percent }) =>
                  `${name}: ${(percent * 100).toFixed(0)}%`
                }
              >
                <Cell fill="#28a745" />
                <Cell fill="#dc3545" />
              </Pie>
              <Tooltip formatter={(value) => [`₹${value}`, "Amount"]} />
              <Legend />
            </PieChart>
          </ResponsiveContainer>
        </div>

        {/* Category Spending Pie Chart */}
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold mb-4">Category-wise Spending</h2>
          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie
                // data={categorySpending}
                data={categoryExpense}
                dataKey="totalExpense"
                nameKey="category"
                cx="50%"
                cy="50%"
                outerRadius={100}
                label={({ name, percent }) =>
                  `${name}: ${(percent * 100).toFixed(0)}%`
                }
              >
                {categoryExpense?.map((_, index: any) => (
                  <Cell
                    key={`cell-${index}`}
                    fill={COLORS[index % COLORS.length]}
                  />
                ))}
              </Pie>
              <Tooltip formatter={(value) => [`₹${value}`, "Amount"]} />
              <Legend />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
